config/routes.rb
Rails.application.routes.draw do
  resources :aria
  root to: 'aria#index'
  devise_for :users
  resources :users

  post "aria/upload", :as =>"upload"
end

app/models/arium.rb
class Arium < ActiveRecord::Base
	
	validates :title, presence: true
	validates :title, length: { minimum:1, maximum: 50 }

	acts_as_ordered_taggable
	acts_as_ordered_taggable_on :genres

	enum arium_type: [:audio, :video]

  belongs_to :user
  has_many :likes
end

app/models/follower.rb
class Follower < ActiveRecord::Base
	belongs_to :user, inverse_of: :followers
	belongs_to :follower, inverse_of: :followers, class_name: 'User',
												foreign_key: 'follower_id'
end

app/models/like.rb
class Like < ActiveRecord::Base
	self.table_name = 'loves'
	belongs_to :user
	belongs_to :arium, counter_cache: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :aria
  has_many :likes
  has_many :liked_aria, through: :likes, source: :arium
  has_many :followers, inverse_of: :user
  has_many :following, inverse_of: :user, class_name: 'Follower',
  										 foreign_key: 'follower_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aria_controller.rb
class AriaController < ApplicationController
  before_action :set_arium, only: [:show, :edit, :update, :destroy]

  # GET /aria
  # GET /aria.json
layout 'backend'
  def index
    @aria = Arium.all
    s3 = Aws::S3::Resource.new
    bucket = s3.bucket('ariafiles')
    @songs = bucket.objects
  end

  # GET /aria/1
  # GET /aria/1.json
  def show
  end

  # GET /aria/new
  def new
    @arium = Arium.new
  end

  # GET /aria/1/edit
  def edit
  end

  # AWS::S3::S3Object.store(sanitize_filename(params[:mp3file].original_filename), params[:mp3file].read, 
  #   BUCKET, :access => :public_read)
  #     redirect_to root_path

  def upload 
    begin
      s3 = Aws::S3::Resource.new
      bucket = s3.bucket('ariafiles')
      obj = Aws::S3::Object.new('ariafiles', sanitize_filename(params[:mp3file].original_filename))
      obj.upload_file(params[:mp3file].path, acl: 'public-read' )
      # obj.upload_file(sanitize_filename(params[:mp3file].original_filename))
      redirect_to root_path
    # rescue
    #   render :text => "Couldn't complete the upload!"
    end
  end

  # def delete
  #   if (params[:song])
  # end

  # POST /aria
  # POST /aria.json
  def create
    @arium = Arium.new(arium_params)

    respond_to do |format|
      if @arium.save
        format.html { redirect_to @arium, notice: 'Arium was successfully created.' }
        format.json { render :show, status: :created, location: @arium }
      else
        format.html { render :new }
        format.json { render json: @arium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aria/1
  # PATCH/PUT /aria/1.json
  def update
    respond_to do |format|
      if @arium.update(arium_params)
        format.html { redirect_to @arium, notice: 'Arium was successfully updated.' }
        format.json { render :show, status: :ok, location: @arium }
      else
        format.html { render :edit }
        format.json { render json: @arium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aria/1
  # DELETE /aria/1.json
  def destroy
    @arium.destroy
    respond_to do |format|
      format.html { redirect_to aria_url, notice: 'Arium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def sanitize_filename(file_name)
      just_filename = File.basename(file_name)
      just_filename.sub(/[^\w\.\-]/,'_')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_arium
      @arium = Arium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arium_params
      params.require(:arium).permit(:title, :description, :love_count, :tag_list, :songs, :bucket)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    if user_signed_in?
      redirect_to  new_arium_path
     else
      redirect_to  new_user_session_path
     end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def download_url_for(song_key)
		s3 = Aws::S3::Resource.new
		s3.bucket('ariafiles').object(song_key).public_url
	end
end

app/helpers/aria_helper.rb
module AriaHelper
end

app/views/aria/_form.html.erb
<%= form_tag upload_path, :method => "post", :multipart => true do %>
    <%= file_field_tag "mp3file" %>
    <%= submit_tag "Upload" %>
<% end %>


<!--<%= form_for(@arium) do |f| %>
  <% if @arium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@arium.errors.count, "error") %> prohibited this arium from being saved:</h2>

      <ul>
      <% @arium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>-->

app/views/aria/edit.html.erb
<h1>Editing Arium</h1>

<%= render 'form' %>

<%= link_to 'Show', @arium %> |
<%= link_to 'Back', aria_path %>

app/views/aria/index.html.erb
<section class="col-sm-4 no-padder bg">
                <section class="vbox">
                  <section class="scrollable hover">
                    <ul class="list-group list-group-lg no-bg auto m-b-none m-t-n-xxs">
                      <% @aria.each_with_index do |arium, index| %>
                        <%= @songs[index].key %>
                        <%= link_to "Download", download_url_for(@songs[index].key) %>
                        <%= link_to "HTML5 Audio", download_url_for(@songs[index].key), :class => "html5" %>
                      <li class="list-group-item clearfix">
                        <a href="#" class="pull-right m-t-sm m-l text-md">
                          <i class="icon-like text"></i>
                        </a>
                        <span class="pull-right m-t-sm m-l text-md"><%= arium.likes_count %></span>
                        <a href="#" class="pull-left thumb-sm m-r">
                          <img src="images/m0.jpg" alt="...">
                        </a>

                        <a class="clear" href="#">
                          <span class="block text-ellipsis"><%= arium.title %></span>
                          <small class="text-muted"><%= arium.description %></small>
                        </a>
                        <section id="audio">
                          No song playing
                        </section>
                      </li>
                      <% end %>
                    </ul>
                  </section>
                </section>
               </section>

app/views/aria/new.html.erb
<%= render 'form' %>

<section class="col-sm-4 no-padder bg">
                <section class="vbox">
                  <section class="scrollable hover">
                    <ul class="list-group list-group-lg no-bg auto m-b-none m-t-n-xxs">
                      <% myrecords = Arium.where(user_id: current_user.id) %>
                      <% myrecords.each do |arium| %>

                      <li class="list-group-item clearfix">
                        <a href="#" class="pull-right m-t-sm m-l text-md">
                          <i class="icon-like text"></i>

                        </a>
                        <span class="pull-right m-t-sm m-l text-md"><%= myrecords.likes_count %></span>
                        <a href="#" class="pull-left thumb-sm m-r">
                          <img src="images/m0.jpg" alt="...">
                        </a>

                        <a class="clear" href="#">
                          <span class="block text-ellipsis"><%= myrecords.title %></span>
                          <small class="text-muted"><%= myrecords.description %></small>
                        </a>
                      </li>
                      <% end %>
                    </ul>
                  </section>
                </section>
              </section>


<!--
              <section class="col-sm-3 no-padder lt">
                <section class="vbox">
                  <section class="scrollable hover">
                    <div class="m-t-n-xxs">
                      <div class="item pos-rlt">
                        <a href="#" class="item-overlay active opacity wrapper-md font-xs">
                          <span class="block h3 font-bold text-info">Find</span>
                          <span class="text-muted">Search the music you like</span>
                          <span class="bottom wrapper-md block">- <i class="icon-arrow-right i-lg pull-right"></i></span>
                        </a>
                        <a href="#">
                          <img class="img-full" src="images/m40.jpg" alt="...">
                        </a>
                      </div>
                      <div class="item pos-rlt">
                        <a href="#" class="item-overlay active opacity wrapper-md font-xs text-right">
                          <span class="block h3 font-bold text-warning text-u-c">Listen</span>
                          <span class="text-muted">Find the peace in your heart</span>
                          <span class="bottom wrapper-md block"><i class="icon-arrow-right i-lg pull-left"></i> -</span>
                        </a>
                        <a href="#">
                          <img class="img-full" src="images/m41.jpg" alt="...">
                        </a>
                      </div>
                      <div class="item pos-rlt">
                        <a href="#" class="item-overlay active opacity wrapper-md font-xs">
                          <span class="block h3 font-bold text-success text-u-c">Share</span>
                          <span class="text-muted">Share the good songs with your loves</span>
                          <span class="bottom wrapper-md block">- <i class="icon-arrow-right i-lg pull-right"></i></span>
                        </a>
                        <a href="#">
                          <img class="img-full" src="images/m42.jpg" alt="...">
                        </a>
                      </div>
                      <div class="item pos-rlt">
                        <a href="#" class="item-overlay active opacity wrapper-md font-xs text-right">
                          <span class="block h3 font-bold text-white text-u-c">2014</span>
                          <span class="text-muted">Find, Listen &amp; Share</span>
                          <span class="bottom wrapper-md block"><i class="icon-arrow-right i-lg pull-left"></i> -</span>
                        </a>
                        <a href="#">
                          <img class="img-full" src="images/m44.jpg" alt="...">
                        </a>
                      </div>
                      <div class="item pos-rlt">
                        <a href="#" class="item-overlay active opacity wrapper-md font-xs">
                          <span class="block h3 font-bold text-danger-lter text-u-c">Top10</span>
                          <span class="text-muted">Selected songs</span>
                          <span class="bottom wrapper-md block">- <i class="icon-arrow-right i-lg pull-right"></i></span>
                        </a>
                        <a href="#">
                          <img class="img-full" src="images/m45.jpg" alt="...">
                        </a>
                      </div>
                    </div>
                  </section>
                </section>
              </section>
-->

app/views/aria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @arium.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @arium.description %>
</p>

<p>
  <strong>Love count:</strong>
  <%= @arium.likes_count %>
</p>

<%= link_to 'Edit', edit_arium_path(@arium) %> |
<%= link_to 'Back', aria_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aria" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Aria" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' %>
    <%= javascript_include_tag "application.js" %>
    <%= csrf_meta_tags %>
  </head>
  
       <%= yield %>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>